"use client";

import { Puzzle } from "lucide-react";
import { Card, PageHeader } from "@/components/ui";
import { mockEngine } from "@/services/mockEngine";

export default function ExercisesPage() {
  const games = mockEngine.getGames();
  const total = games.reduce((a, g) => a + g.exerciseCount, 0);
  const levels = games.reduce((a, g) => a + g.levelCount, 0);

  return (
    <div>
      <PageHeader title="Exercise Library" subtitle="Engine-generated exercises across registered games." />
      <Card>
        <div className="flex items-center gap-3 text-slate-600">
          <Puzzle size={24} className="text-brand-600" />
          <div>
            <p className="text-sm font-medium text-slate-800">Content pool overview</p>
            <p className="text-sm text-slate-500">{total} exercises across {levels} levels from {games.length} games. In-depth browsing is generated by the Engine on demand.</p>
          </div>
        </div>
      </Card>
    </div>
  );
}
