"use client";

import { useState } from "react";
import { ArrowLeft, Check, Loader2, Rocket } from "lucide-react";
import { mockEngine } from "@/services/mockEngine";
import { Button, Card, PageHeader } from "@/components/ui";
import type { ExerciseType, PhonemePosition, RegisterGameInput } from "@/types/engine";

const EXERCISE_TYPES: ExerciseType[] = ["picture_naming", "word_repetition", "minimal_pair", "sound_identification"];
const POSITIONS: PhonemePosition[] = ["initial", "medial", "final"];
const MECHANICS = ["Movement", "Collection", "Multiple Choice", "Timed Challenge", "Drag and Drop", "Resource", "Energy"];
const MEDIA = ["image", "audio", "video"];

const STEPS = ["Basic", "Capabilities", "Mechanics", "Content", "Review"];

export default function NewGamePage() {
  const [step, setStep] = useState(0);
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState<null | { gameId: string; levels: number; exercises: number; key: string }>(null);

  const [form, setForm] = useState<RegisterGameInput>({
    name: "",
    description: "",
    developer: "",
    version: "1.0.0",
    ageRangeMin: 5,
    ageRangeMax: 8,
    exerciseTypes: [],
    positions: [],
    difficultyMin: 1,
    difficultyMax: 10,
    mechanics: [],
    theme: "",
    wordStyle: "",
    preferredContent: "",
    mediaTypes: [],
  });

  function toggleArr<K extends keyof RegisterGameInput>(key: K, val: string) {
    const cur = form[key] as string[];
    setForm((f) => ({
      ...f,
      [key]: cur.includes(val) ? cur.filter((x) => x !== val) : [...cur, val],
    }));
  }

  function canContinue() {
    if (step === 0) return form.name && form.description;
    if (step === 1) return form.exerciseTypes.length > 0 && form.positions.length > 0;
    if (step === 2) return form.mechanics.length > 0;
    if (step === 3) return form.theme && form.mediaTypes.length > 0;
    return true;
  }

  function register() {
    setGenerating(true);
    const game = mockEngine.registerGame(form);
    setTimeout(() => {
      const gen = mockEngine.generateContent(game.id);
      setGenerating(false);
      setDone({ gameId: game.id, ...gen, key: game.apiKey });
    }, 1800);
  }

  return (
    <div>
      <Button variant="ghost" href="/games"><ArrowLeft size={16} /> Back to Games</Button>
      <PageHeader title="Register Game" subtitle="Onboard a new skin. On registration the Engine generates its content pool." />

      {done ? (
        <Card className="max-w-2xl">
          <div className="flex items-center gap-3 text-emerald-600"><Check size={22} /> <h3 className="text-lg font-bold text-slate-900 dark:text-white">Game registered</h3></div>
          <dl className="mt-4 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
            <div className="rounded-lg border border-slate-100 px-4 py-3 dark:border-slate-800"><dt className="text-xs text-slate-500 dark:text-slate-400">Game ID</dt><dd className="font-mono text-slate-800 dark:text-slate-100">{done.gameId}</dd></div>
            <div className="rounded-lg border border-slate-100 px-4 py-3 dark:border-slate-800"><dt className="text-xs text-slate-500 dark:text-slate-400">API key</dt><dd className="font-mono text-slate-800 dark:text-slate-100">{done.key}</dd></div>
            <div className="rounded-lg border border-slate-100 px-4 py-3 dark:border-slate-800"><dt className="text-xs text-slate-500 dark:text-slate-400">Levels generated</dt><dd className="font-semibold text-slate-800 dark:text-slate-100">{done.levels}</dd></div>
            <div className="rounded-lg border border-slate-100 px-4 py-3 dark:border-slate-800"><dt className="text-xs text-slate-500 dark:text-slate-400">Exercises generated</dt><dd className="font-semibold text-slate-800 dark:text-slate-100">{done.exercises}</dd></div>
          </dl>
          <p className="mt-3 text-xs text-slate-400 dark:text-slate-500">Content auto-generated by the Engine from the declared capabilities.</p>
          <div className="mt-5 flex gap-2">
            <Button variant="secondary" href="/games">Done</Button>
            <Button href={`/games/${done.gameId}/configuration`}>Configure injection</Button>
          </div>
        </Card>
      ) : (
        <Card>
          <div className="mb-6 flex items-center gap-2">
            {STEPS.map((s, i) => (
              <div key={s} className="flex items-center gap-2">
                <div className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-semibold ${i === step ? "bg-brand-600 text-white" : i < step ? "bg-brand-100 text-brand-700 dark:bg-brand-900/40 dark:text-brand-300" : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400"}`}>
                  {i < step ? <Check size={12} /> : i + 1}
                </div>
                <span className={`text-xs font-medium ${i === step ? "text-brand-700" : "text-slate-500 dark:text-slate-400"}`}>{s}</span>
              </div>
            ))}
          </div>

          {step === 0 && (
            <div className="space-y-4">
              <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Game name</span><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Description</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" rows={3} /></label>
              <div className="grid grid-cols-2 gap-4">
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Developer</span><input value={form.developer} onChange={(e) => setForm({ ...form, developer: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Version</span><input value={form.version} onChange={(e) => setForm({ ...form, version: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              </div>
            </div>
          )}

          {step === 1 && (
            <div className="space-y-5">
              <div>
                <p className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-300">Supported exercise types</p>
                <div className="flex flex-wrap gap-2">
                  {EXERCISE_TYPES.map((t) => (
                    <button key={t} type="button" onClick={() => toggleArr("exerciseTypes", t)} className={`rounded-lg border px-3 py-1.5 text-sm ${form.exerciseTypes.includes(t) ? "border-brand-600 bg-brand-600 text-white" : "border-slate-300 text-slate-600 dark:border-slate-700 dark:text-slate-300"}`}>{t.replace("_", " ")}</button>
                  ))}
                </div>
              </div>
              <div>
                <p className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-300">Supported phoneme positions</p>
                <div className="flex flex-wrap gap-2">
                  {POSITIONS.map((p) => (
                    <button key={p} type="button" onClick={() => toggleArr("positions", p)} className={`rounded-lg border px-3 py-1.5 text-sm capitalize ${form.positions.includes(p) ? "border-brand-600 bg-brand-600 text-white" : "border-slate-300 text-slate-600 dark:border-slate-700 dark:text-slate-300"}`}>{p}</button>
                  ))}
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Min difficulty</span><input type="number" min={1} max={10} value={form.difficultyMin} onChange={(e) => setForm({ ...form, difficultyMin: +e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Max difficulty</span><input type="number" min={1} max={10} value={form.difficultyMax} onChange={(e) => setForm({ ...form, difficultyMax: +e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              </div>
            </div>
          )}

          {step === 2 && (
            <div>
              <p className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-300">Supported game mechanics</p>
              <div className="flex flex-wrap gap-2">
                {MECHANICS.map((m) => (
                  <button key={m} type="button" onClick={() => toggleArr("mechanics", m)} className={`rounded-lg border px-3 py-1.5 text-sm ${form.mechanics.includes(m) ? "border-brand-600 bg-brand-600 text-white" : "border-slate-300 text-slate-600 dark:border-slate-700 dark:text-slate-300"}`}>{m}</button>
                ))}
              </div>
            </div>
          )}

          {step === 3 && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Theme</span><input value={form.theme} onChange={(e) => setForm({ ...form, theme: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Word style</span><input value={form.wordStyle} onChange={(e) => setForm({ ...form, wordStyle: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              </div>
              <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Preferred content</span><input value={form.preferredContent} onChange={(e) => setForm({ ...form, preferredContent: e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              <div className="grid grid-cols-2 gap-4">
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Min age</span><input type="number" value={form.ageRangeMin} onChange={(e) => setForm({ ...form, ageRangeMin: +e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
                <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600 dark:text-slate-300">Max age</span><input type="number" value={form.ageRangeMax} onChange={(e) => setForm({ ...form, ageRangeMax: +e.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" /></label>
              </div>
              <div>
                <p className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-300">Supported media</p>
                <div className="flex flex-wrap gap-2">
                  {MEDIA.map((m) => (
                    <button key={m} type="button" onClick={() => toggleArr("mediaTypes", m)} className={`rounded-lg border px-3 py-1.5 text-sm capitalize ${form.mediaTypes.includes(m) ? "border-brand-600 bg-brand-600 text-white" : "border-slate-300 text-slate-600 dark:border-slate-700 dark:text-slate-300"}`}>{m}</button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {step === 4 && (
            <div className="space-y-3">
              <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">Review configuration</p>
              <dl className="space-y-2 text-sm">
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Name</dt><dd className="font-medium text-slate-800 dark:text-slate-100">{form.name}</dd></div>
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Exercise types</dt><dd className="text-slate-800 dark:text-slate-100">{form.exerciseTypes.map((t) => t.replace("_", " ")).join(", ")}</dd></div>
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Positions</dt><dd className="text-slate-800 dark:text-slate-100 capitalize">{form.positions.join(", ")}</dd></div>
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Difficulty</dt><dd className="text-slate-800 dark:text-slate-100">{form.difficultyMin}–{form.difficultyMax}</dd></div>
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Mechanics</dt><dd className="text-slate-800 dark:text-slate-100">{form.mechanics.join(", ")}</dd></div>
                <div className="flex justify-between"><dt className="text-slate-500 dark:text-slate-400">Theme</dt><dd className="text-slate-800 dark:text-slate-100">{form.theme}</dd></div>
              </dl>
            </div>
          )}

          <div className="mt-6 flex justify-between border-t border-slate-100 pt-4 dark:border-slate-800">
            <Button variant="secondary" onClick={() => setStep((s) => s - 1)} disabled={step === 0}>Back</Button>
            {step < 4 ? (
              <Button onClick={() => setStep((s) => s + 1)} disabled={!canContinue()}>Continue</Button>
            ) : (
              <Button onClick={register} disabled={generating}>
                {generating ? (<><Loader2 className="animate-spin" size={16} /> Generating content…</>) : (<><Rocket size={16} /> Register Game</>)}
              </Button>
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
